name: Local Docker Deployment

on:
  push:
    branches:
      - master


jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker rmi personal-web || true
          docker build -t personal-web .

      - name: Stop and Remove Existing Container
        run: |
          docker stop personal-web || true
          docker rm personal-web || true

      - name: Run Docker Container
        env:
          PORT: ${{ secrets.PORT }}
          PORT_FORWARD: ${{ secrets.PORT_FORWARD }}
        run: docker run -d -p $PORT:$PORT_FORWARD --name personal-web personal-web