name: Local Docker Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_URL=${{ secrets.DB_URL }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "PORT_FORWARD=${{ secrets.PORT_FORWARD }}" >> .env

      - name: Stop and Remove Existing Containers
        run: |
          docker-compose down || true

      - name: Build and Deploy Docker Containers
        run: |
          docker-compose build
          docker-compose up -d
